server:
  port: 0
spring:
  application:
    name: kafkapp-payment-command
  cloud:
    stream:
      bindings:
        input:
          group: messages-group-${random.value}
          destination: kafkapp
#          durableSubscription: true
